apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tinywebserver
spec:
  type: ClusterIP          # MySQL 仅集群内访问
  clusterIP: None          # Headless Service，配合 StatefulSet DNS
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
